### ISSUE TITLE
spawn fpcalc ENOENT

### ISSUE THREAD

**Issue by PalexDrod** [parshap/node-fpcalc#6]
I can't find a fix to this problem. Can I get some help pls?

> Error: spawn fpcalc ENOENT
>     at exports._errnoException (util.js:1018:11)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
>     at onErrorNT (internal/child_process.js:367:16)
>     at _combinedTickCallback (internal/process/next_tick.js:80:11)
>     at process._tickCallback (internal/process/next_tick.js:104:9)
>     at Module.runMain (module.js:606:11)
>     at run (bootstrap_node.js:390:7)
>     at startup (bootstrap_node.js:150:9)
>     at bootstrap_node.js:505:3

**Comment by parshap** [comment]
Do you have fpcalc installed? See the readme section on "Installing Chromaprint" https://github.com/parshap/node-fpcalc#installing-chromaprint

**Comment by PranavRudra** [comment]
I'm having the exact same issue. I've installed chromaprint using brew on OSX but my terminal isn't recognizing the fpcalc command. I even tried installing the fpcalc CLI directly from AcoustID, but it didn't solve the issue.

**Comment by parshap** [comment]
Is `fpcalc` in your `$PATH`? What happens if you run` fpcalc` in the same terminal that you're running your node script from? You can use the [`command` option](https://github.com/parshap/node-fpcalc#fpcalcfile-options-callback) to give a full path to the `fpcalc` executable.

**Comment by zeke** [comment]
I ran into this issue today too. Worked around it by downloading a build of chromaprint from https://acoustid.org/chromaprint

**Comment by loretoparisi** [comment]
It seems that `brew` install `chromaprint` but the build fails:

```
$ brew info chromaprint
chromaprint: stable 1.4.3 (bottled)
Core component of the AcoustID project (Audio fingerprinting)
https://acoustid.org/chromaprint
/usr/local/Cellar/chromaprint/1.4.3 (10 files, 108.4KB) *
  Poured from bottle on 2018-07-11 at 11:04:43
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/chromaprint.rb
==> Dependencies
Build: cmake ✘
```
